apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: catalog-local-build
spec:
  inputs:
    resources:
      - name: catalog-source
        type: git
  steps:
    - name: gradle-build
      image: gradle
      command: ["gradle"]
      args:
        - "build"
