apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-push-deploy
spec:
  resources:
    - name: source
      type: git
    - name: inv-source
      type: git
    - name: image
      type: image
    - name: inv-image
      type: image
  tasks:
    - name: mysql-deployment
      taskRef:
        name: mysql-deploy-using-yaml
      resources:
        inputs:
          - name: source
            resource: source
          - name: image
            resource: image
      params:
        - name: pathToYamlFile
          value: "bluecompute-os/bluecompute-ce/charts/mysql/templates"
        - name: imageUrl
          value: "index.docker.io/mysql"
        - name: imageTag
          value: "5.7.14"
    - name: inventory-local-build
      taskRef:
        name: inv-local-build
      runAfter:
        - mysql-deployment
      resources:
        inputs:
          - name: inv-source
            resource: inv-source
    - name: inventory-build-push
      taskRef:
        name: buildah
      runAfter:
        - inventory-local-build
      resources:
        inputs:
          - name: inv-source
            resource: inv-source
          - name: inv-image
            resource: inv-image
    - name: inventory-deploy
      taskRef:
        name: inv-deploy-using-yaml
      runAfter:
        - inventory-build-push
      resources:
        inputs:
          - name: source
            resource: source
          - name: inv-image
            resource: inv-image
      params:
        - name: pathToYamlFile
          value: "bluecompute-os/bluecompute-ce/charts/inventory/templates"
        - name: imageUrl
          value: "index.docker.io/ibmcase/bluecompute-inventory"
        - name: imageTag
          value: "openshift"
