apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
spec:
  type: git
  params:
    - name: revision
      value: issue_221
    - name: url
      value: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes
