apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: inv-source
spec:
  type: git
  params:
    - name: revision
      value: spring
    - name: url
      value: https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory
